build/cs-studio-jenkins-checkstyle, pom.xml
Add unit tests to dls-controls product build.
Add copy of checkstyle config from main CSS project
=> Jenkins build

plugins/org.csstudio.dls.product/plugin_customization.ini
=> Remove configured address list since it should be automatic.

repository/cs-studio.p2.inf
Further updates to configuration to fix nightlybuild start issues
=> Add locking and custom-name local config

repository/cs-studio.product
* Remove org.csstudio.pvmanager.jdbc.feature as it is unused
* Remove XX:MaxPermSize as it is not used in Java 8
=> Remove configuration causing errors on startup.

plugins/org.csstudio.dls.product/plugin_customization.ini
Remove configuration keys for unincluded plugins and correct data for DLS product
=> Cleanup config

plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/editparts/MenuMuxEditPart.java
=> Write select MenuMux index value to control PV.

build/cs-studio-jenkins-checkstyle
=> Add HTML files to checkstyle.

plugins/org.csstudio.trends.databrowser2.command/.classpath, plugins/org.csstudio.trends.databrowser2.command/.project, plugins/org.csstudio.trends.databrowser2.command/META-INF/MANIFEST.MF, plugins/org.csstudio.trends.databrowser2.command/build.properties, plugins/org.csstudio.trends.databrowser2.command/plugin.xml, plugins/org.csstudio.trends.databrowser2.command/src/org/csstudio/trends/databrowser2/command/NewWindowHandler.java
This defines a command and a handler that can be called from scripts. It
probably still needs some work.
@nickbattam
=> New databrowser window command.

features/org.csstudio.dls.feature/feature.xml, plugins/org.csstudio.trends.databrowser2.command/META-INF/MANIFEST.MF, plugins/org.csstudio.trends.databrowser2.command/pom.xml, plugins/pom.xml
@nickbattam nothing particularly interesting here.
=> Add databrowser command to dls product build.

build/cs-studio-jenkins-checkstyle, pom.xml
Update to newer version of checkstyle.
@nickbattam
=> Ensure all relevant files are found by checkstyle.

pom.xml
@willrogers  This adds an explicit list of directories to include in the checkstyle run.
=> Restrict includes 

features/org.csstudio.dls.feature/feature.xml, plugins/org.diirt.datasource.fa.test/.classpath, plugins/org.diirt.datasource.fa.test/.project, plugins/org.diirt.datasource.fa.test/META-INF/MANIFEST.MF, plugins/org.diirt.datasource.fa.test/build.properties, plugins/org.diirt.datasource.fa.test/fragment.xml, plugins/org.diirt.datasource.fa.test/pom.xml, plugins/org.diirt.datasource.fa.test/src/org/diirt/datasource/fa/FAChannelHandlerTest.java, plugins/org.diirt.datasource.fa.test/src/org/diirt/datasource/fa/FADataSourceTest.java, plugins/org.diirt.datasource.fa.test/src/org/diirt/datasource/fa/FADataSourceTypeAdapterTest.java, plugins/org.diirt.datasource.fa/.classpath, plugins/org.diirt.datasource.fa/.project, plugins/org.diirt.datasource.fa/META-INF/MANIFEST.MF, plugins/org.diirt.datasource.fa/OSGI-INF/ds_fa.xml, plugins/org.diirt.datasource.fa/build.properties, plugins/org.diirt.datasource.fa/plugin.xml, plugins/org.diirt.datasource.fa/pom.xml, plugins/org.diirt.datasource.fa/src/org/diirt/datasource/fa/FAChannelHandler.java, plugins/org.diirt.datasource.fa/src/org/diirt/datasource/fa/FADataSource.java, plugins/org.diirt.datasource.fa/src/org/diirt/datasource/fa/FADataSourceProvider.java, plugins/org.diirt.datasource.fa/src/org/diirt/datasource/fa/FADataSourceTypeAdapter.java, plugins/pom.xml
The PVManager datasource allows you to use `fa://` pvs like other pvs.
=> Fastarchiver

plugins/org.csstudio.dls.product/plugin_customization.ini
Can someone build this and make sure it works for them?
@nickbattam @mfurseman
=> Use diirt config local to CSS installation.

plugins/org.csstudio.opibuilder.dlsopitests/start_converted_panels.sh
Although this hasn't been built in the nightly, it's not actually built anyway, so I don't think that's a major issue. In an effort to remove differences between dls-4.2.x and integration I am opening this pull request early, feel free to hold of merging until you're happy as well.
=> Added script to open converted panels

plugins/org.csstudio.trends.databrowser2.command/plugin.xml
Remove undefined category errors at startup
=> Declare category for Databrowser command

plugins/org.csstudio.dls.product/pom.xml, plugins/org.csstudio.dls.product/update-splash-screen.sh
Adds the version number stored in about.mappings to the splash screen at build time.
=> Update splash screen at compile time

plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/editparts/EdmSymbolEditpart.java
Handle VEnum values in EDM symbol widget.
@nickbattam  @mfurseman
=> Symbol enum

plugins/org.csstudio.dls.product/plugin.xml
This merges #66 into dls-4.2.x.
=> Prevent team synchronizing perspective and views from showing - DLS-4.2.x

repository/cs-studio.product
This is the required to change to recover EDM functionality after placing it in a seperate feature as per https://github.com/ControlSystemStudio/cs-studio/issues/1594.
=> Add new EDM feature to bring in previous EDM functionality

plugins/org.csstudio.dls.product/plugin.xml, repository/cs-studio.product
Add the CA Snooper feature to our product
=> CA Snooper

pom.xml, repository/cs-studio.product
@willrogers Updates to resolve issues identified on #73
=> V43 update (integration)

plugins/org.csstudio.dls.product/about.mappings, pom.xml, repository/cs-studio.product
@willrogers Update the DLS product (master) branch to reference v4.3
=> Update DLS product to 4.3 (master)

repository/cs-studio.product
The change this depends on is now merged into CS-Studio.
=> Add new EDM feature to bring in previous EDM functionality - Master

plugins/org.csstudio.dls.product/plugin.xml
This implements #82 and #77 on the 4.2.x branch.
Cherry-picked commits: e90addf and 3654141.
=> Keep standalone summary open and show all perspectives in Window menu - [integration-4.2.x]

repository/cs-studio.product
As #70 but cherry-picked for 4.2.x.
=> Add the CA Snooper feature to our product - [dls-4.2.x]

plugins/org.csstudio.dls.product/plugin.xml
=> Better default perspectives and views under the Window menu - [master]

features/org.csstudio.dls.product.configuration.feature/build.properties, features/org.csstudio.dls.product.configuration.feature/rootfiles/css.sh
=> Add CSS wrapper script - [dls-4.2.x]

features/org.csstudio.dls.product.configuration.feature/build.properties, features/org.csstudio.dls.product.configuration.feature/rootfiles/css.sh
=> Run script [master]

plugins/org.csstudio.dls.product/about.mappings, repository/cs-studio.product
=> Update version to 4.2.beta2

plugins/org.csstudio.dls.product/plugin.xml
@nickbattam this one hadn't made it to `dls-4.2.x`.
=> Standalone and perspectives

features/org.csstudio.dls.product.configuration.feature/build.properties, features/org.csstudio.dls.product.configuration.feature/rootfiles/css.sh, plugins/org.csstudio.dls.product/plugin.xml, pom.xml, repository/cs-studio.product
=> Perspective feature

repository/cs-studio.product
=> Add archive appliance reader plugin.

pom.xml
=> Revert to Mars p2 repo now it includes 4.5.2.

pom.xml
=> Add local-dev maven profile

plugins/org.csstudio.dls.product/font.def
=> Update default font selection to match converter (4.2.x)

plugins/org.csstudio.dls.product/font.def
=> Update default font selection to match converter (master)

features/org.csstudio.dls.product.configuration.feature/rootfiles/css.sh, features/org.csstudio.dls.product.feature/feature.xml, plugins/org.csstudio.openfile.newwindow.test/.classpath, plugins/org.csstudio.openfile.newwindow.test/.project, plugins/org.csstudio.openfile.newwindow.test/META-INF/MANIFEST.MF, plugins/org.csstudio.openfile.newwindow.test/build.properties, plugins/org.csstudio.openfile.newwindow.test/pom.xml, plugins/org.csstudio.openfile.newwindow.test/src/org/csstudio/openfile/beamlines/LinkUpdaterTest.java, plugins/org.csstudio.openfile.newwindow.test/src/org/csstudio/openfile/beamlines/WindowSpecParserTest.java, plugins/org.csstudio.openfile.newwindow.test/src/org/csstudio/openfile/newwindow/LinkUpdaterTest.java, plugins/org.csstudio.openfile.newwindow.test/src/org/csstudio/openfile/newwindow/WindowSpecParserTest.java, plugins/org.csstudio.openfile.newwindow/.classpath, plugins/org.csstudio.openfile.newwindow/.project, plugins/org.csstudio.openfile.newwindow/META-INF/MANIFEST.MF, plugins/org.csstudio.openfile.newwindow/build.properties, plugins/org.csstudio.openfile.newwindow/plugin.xml, plugins/org.csstudio.openfile.newwindow/pom.xml, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/LinkUpdater.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/Messages.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/OpenNewWindow.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/PerspectiveHelper.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/Plugin.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/WindowManagementException.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/WindowOpener.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/WindowSpec.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/WindowSpecParser.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/messages.properties, plugins/pom.xml
=> Beamline windows

repository/cs-studio.product
=> Remove dependency on legacy casnooperUi feature

pom.xml
=> Remove Maven error in Eclipse by ignoring it in the pom.

pom.xml
=> Use central 4.3 repos from CS-Studio.

plugins/org.csstudio.opibuilder.dlsopitests/xygraph.opi, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/DawnXYGraphEditPart.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/DawnXYGraphModel.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/XYGraphDataProvider.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/XygraphDataProvider.java
For review now that the changes to swt-xy-graph have built for Dawn @nickbattam
=> Css262 xygraph wr

plugins/org.csstudio.opibuilder.dlsopitests/xygraph.opi, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/DawnXYGraphEditPart.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/DawnXYGraphModel.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/XYGraphDataProvider.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/XygraphDataProvider.java
=> Xygraph 42x

plugins/org.csstudio.opibuilder.dlsopitests/build.properties, pom.xml
@nickbattam looks like the maven error fix never made it into integration ...
=> Opitests master

plugins/org.csstudio.opibuilder.dlsopitests/build.properties
=> Add more of dlsopitests into built plugin.

plugins/org.csstudio.opibuilder.dlsopitests/xygraph.opi, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/DawnXYGraphEditPart.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/DawnXYGraphModel.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/XYGraphDataProvider.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/XygraphDataProvider.java
@willrogers XYGraph updates into master
=> Css262 xygraph (master)

plugins/org.csstudio.opibuilder.dlsopitests/build.properties
=> Remove reference to missing file (master)

pom.xml
=> Update tycho-extras to use tycho version

pom.xml
=> Dawn stable

pom.xml
=> Move to using stable Dawn p2 site (version 2.1)

pom.xml
=> Move to using stable Dawn p2 site (version 2.1) (dls-4.2.x)

pom.xml
=> Move to using stable Dawn p2 site (version 2.1) (integration-4.2.x)

plugins/org.csstudio.dls.product.5064/plugin_customization.ini, plugins/org.csstudio.dls.product.6064/plugin_customization.ini
@willrogers Copy of #144 for master branch
=> Archive keys master

plugins/org.csstudio.dls.product.5064/about.mappings, plugins/org.csstudio.dls.product.6064/about.mappings, pom.xml, repository/cs-studio.product, repository/pom.xml
=> Update version numbers for master to 4.4

repository/cs-studio.product
=> Increase JVM memory pool to 3Gb

plugins/org.csstudio.dls.product.5064/plugin_customization.ini, plugins/org.csstudio.dls.product.6064/plugin_customization.ini
=> Add default True for auto browser refresh

features/org.csstudio.dls.product.feature/feature.xml
=> Add osgiX bundle to provide sun.misc package.

plugins/org.csstudio.trends.databrowser2.command/src/org/csstudio/trends/databrowser2/command/NewWindowHandler.java
This allows better handling of saving the file.
@nickbattam
=> Work with Eclipse paths in new databrowser window command.

plugins/org.csstudio.trends.databrowser2.command/src/org/csstudio/trends/databrowser2/command/NewWindowHandler.java
Merged in error; should have gone into integration
Reverts dls-controls/org.csstudio.dls.product#156
=> Revert "Work with Eclipse paths in new databrowser window command."

plugins/org.csstudio.trends.databrowser2.command/META-INF/MANIFEST.MF, plugins/org.csstudio.trends.databrowser2.command/src/org/csstudio/trends/databrowser2/command/NewWindowHandler.java
=> Db save master

plugins/org.csstudio.trends.databrowser2.command/META-INF/MANIFEST.MF, plugins/org.csstudio.trends.databrowser2.command/src/org/csstudio/trends/databrowser2/command/NewWindowHandler.java
=> Db save 4 3

plugins/org.csstudio.dls.product.5064/plugin_customization.ini, plugins/org.csstudio.dls.product.6064/plugin_customization.ini, plugins/org.csstudio.dls.product.common/default_widgets.opi, plugins/org.csstudio.dls.product.common/font.def
=> Update DLS product config to respect new pixel-based fonts

plugins/org.csstudio.opibuilder.dlsopitests/required_plugins.txt
Update expected list used by tests to match renamed dls-product plugins
=> Update product plugin names

plugins/org.csstudio.openfile.newwindow.test/src/org/csstudio/openfile/newwindow/LinkUpdaterTest.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/intensitygraph/DawnIntensityGraphModel.java, plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/editparts/EdmSymbolEditpart.java
=> Checkstyle (master)

plugins/org.csstudio.openfile.newwindow.test/src/org/csstudio/openfile/newwindow/LinkUpdaterTest.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/intensitygraph/DawnIntensityGraphModel.java, plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/editparts/EdmSymbolEditpart.java
@willrogers  Fix checkstyle warnings
=> Checkstyle

plugins/org.csstudio.dls.product.5064/plugin_customization.ini, plugins/org.csstudio.dls.product.6064/plugin_customization.ini, plugins/org.csstudio.dls.product.common/default_widgets.opi, plugins/org.csstudio.dls.product.common/font.def
@willrogers  Update dls-product to expect pixel-fonts
=> Updates to support pixel fonts (master)

plugins/org.csstudio.dls.product.5064/about.mappings, plugins/org.csstudio.dls.product.6064/about.mappings, pom.xml, repository/cs-studio.product, repository/pom.xml
=> Update product version to 4.5 (integration)

plugins/org.csstudio.dls.product.5064/about.mappings, plugins/org.csstudio.dls.product.6064/about.mappings, pom.xml, repository/cs-studio.product, repository/pom.xml
=> Update product version to 4.5 (master)

features/org.csstudio.dls.product.feature/feature.xml, plugins/org.csstudio.dls.product.5064/META-INF/MANIFEST.MF, plugins/org.csstudio.dls.product.6064/META-INF/MANIFEST.MF, plugins/org.csstudio.dls.product.common/META-INF/MANIFEST.MF, repository/cs-studio.product
@nickbattam merging to get this into the nightly build.
=> Css 305 44

plugins/org.csstudio.dls.product.5064/plugin_customization.ini, plugins/org.csstudio.dls.product.6064/plugin_customization.ini
=> Correctly specify repeater port value.

repository/cs-studio.product
=> Increase JVM memory pool to 3Gb (4.4)

repository/cs-studio.product
=> Increase JVM memory pool to 3Gb (master)

plugins/org.csstudio.dls.product.5064/plugin_customization.ini, plugins/org.csstudio.dls.product.6064/plugin_customization.ini
=> Make Databrowser the default perspective.

features/org.csstudio.dls.product.feature/rootfiles/css.sh
=> Escape macro and links but not filepath (4.4)

features/org.csstudio.dls.product.feature/rootfiles/css.sh
=> Escape macro and links but not filepath

plugins/org.csstudio.dls.product.common/font.def
Test Default fontsize change for comparison with (unchanged) master
=> Fontsize (4.4.x)

plugins/org.csstudio.dls.product.common/font.def
=> Recalculate pixel font sizes from 4.3.x point sizes

features/org.csstudio.dls.product.feature/rootfiles/css.sh
@nickbattam @mfurseman this is working on the nightly.
=> Escaped args 44

features/org.csstudio.dls.product.feature/rootfiles/css.sh
@nickbattam @mfurseman this is working on the nightly.
=> Escaped args

features/org.csstudio.dls.product.feature/rootfiles/css.sh
@willrogers This is #192 cherry picked onto 4.5/master branch
=> Add workbench (xmi) argument support to launch script

plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/OpenNewWindow.java
=> Increase "new java vm" timeout to allow for slower application startup

plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/OpenNewWindow.java
=> Timeout (dls-4.4.x)

features/org.csstudio.dls.product.feature/rootfiles/css.sh
=> Add workbench (xmi) argument support to launch script (master)

plugins/org.csstudio.opibuilder.dlsopitests/required_plugins.txt
@willrogers  #160 cherry picked to master
=> Update product plugin names (master)

plugins/org.csstudio.opibuilder.dlsopitests/required_plugins.txt
@willrogers  #160 cherry picked to dls-4.4.x
=> Update product plugin names (4.4.x)

features/org.csstudio.dls.product.feature/rootfiles/css.sh, plugins/org.csstudio.dls.product.5064/plugin_customization.ini, plugins/org.csstudio.dls.product.6064/plugin_customization.ini
=> Move dls-product workspaces (4.4)

features/org.csstudio.dls.product.feature/rootfiles/css.sh, repository/cs-studio.p2.inf
=> Move workspace locations (integration)

features/org.csstudio.dls.product.feature/rootfiles/css.sh, repository/cs-studio.p2.inf
=> Update default workspace (master)

features/org.csstudio.dls.product.feature/rootfiles/configuration/databrowser.nws, features/org.csstudio.dls.product.feature/rootfiles/css.sh
=> Make default behaviour of css.sh to launch a new databrowser window.

plugins/org.csstudio.openfile.newwindow.test/src/org/csstudio/openfile/newwindow/WindowSpecParserTest.java
=> Fix test for changed new window behaviour.

features/org.csstudio.dls.product.feature/rootfiles/css.sh
=> Workspaces

features/org.csstudio.dls.product.feature/rootfiles/configuration/databrowser.nws, features/org.csstudio.dls.product.feature/rootfiles/css.sh, plugins/org.csstudio.openfile.newwindow.test/src/org/csstudio/openfile/newwindow/WindowSpecParserTest.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/OpenNewWindow.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/WindowSpec.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/WindowSpecParser.java
=> Perspective file

plugins/org.csstudio.dls.product.dev/about.mappings, plugins/org.csstudio.dls.product/about.mappings, repository/cs-studio.product, repository/pom.xml
=> Update release 4.4.0 branding

plugins/org.csstudio.opibuilder.dlsopitests/required_plugins.txt
@nickbattam no need to fix this for the release.
=> Change list of required plugins to reflect new products.

features/org.csstudio.dls.product.feature/rootfiles/configuration/databrowser.nws, features/org.csstudio.dls.product.feature/rootfiles/css.sh, plugins/org.csstudio.openfile.newwindow.test/src/org/csstudio/openfile/newwindow/WindowSpecParserTest.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/OpenNewWindow.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/WindowSpec.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/WindowSpecParser.java
@nickbattam this one includes the other so I will close the other one.
=> Workspaces master

features/org.csstudio.dls.product.feature/rootfiles/css.sh, plugins/org.csstudio.dls.product.common/plugin_customization.ini
=> 380 products master

features/org.csstudio.dls.product.feature/rootfiles/css.sh, plugins/org.csstudio.dls.product.common/plugin_customization.ini
=> 380 products

pom.xml
@nickbattam no doubt this will be overridden by the build system but it shows willing.
=> Use Tycho version 1.0.0.

features/org.csstudio.dls.product.feature/rootfiles/css.sh
@willrogers as #255 for 4.4 branch
=> Extend launch script to pass EPICS environment variables to diirt (integration-4.4)

features/org.csstudio.dls.product.feature/rootfiles/css.sh
@willrogers If there is no dirty workspace this sets the diirt preferences correctly.
To roll-out for i14 we would need to wait for a fix to diirt/cs-studio preference or remove the diirt preference cache in the i14 launch script.
=> Extend launch script to pass EPICS environment variables to diirt (integration)

features/org.csstudio.dls.product.feature/rootfiles/css.sh
=> Extend launch script to delete cached DIIRT/EPICS preferences (integration)

features/org.csstudio.dls.product.feature/rootfiles/css.sh
=> Pass EPICS environment variables to DIIRT (dls-4.4)

features/org.csstudio.dls.product.feature/rootfiles/css.sh
=> Pass EPICS environment variables to DIIRT (master)

plugins/org.csstudio.dls.product.common/plugin_customization.ini, plugins/org.csstudio.trends.databrowser2.command/src/org/csstudio/trends/databrowser2/command/NewWindowHandler.java
=> Auto refresh

pom.xml
=> Tweak pom.xml to allow Neon build (master)

plugins/org.csstudio.trends.databrowser2.command/src/org/csstudio/trends/databrowser2/command/NewWindowHandler.java
@nickbattam this refresh proved necessary when opening files from Python scripts.
=> Revert "Remove refresh from databrowser command."

features/org.csstudio.dls.product.feature/rootfiles/css.sh, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/OpenNewWindow.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/Plugin.java
On the first run, if a .nws file was launched, reuse a workbench window.
Otherwise, open a new one.
@mfurseman @nickbattam anyone want to merge with their eyes shut?
=> Better handling of windows with .nws file.

plugins/org.csstudio.dls.product.common/plugin_customization.ini
=> Perspective bar text

plugins/org.csstudio.trayicon/src/org/csstudio/trayicon/TrayApplicationWorkbenchWindowAdvisor.java
@willrogers Bugfix and some comment cleanup.
If you're happy with this I'll port the branch to cs-studio/core
=> Block prompt when multiple windows open

plugins/org.csstudio.dls.product.common/plugin_customization.ini
The default behaviour caused a lot of problems.
@willrogers
=> Preference to automatically refresh workspace when necessary. (dls-4.4)

features/org.csstudio.dls.product.feature/rootfiles/css.sh, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/OpenNewWindow.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/Plugin.java
=> Better handling of windows (dls-4.4)

pom.xml
=> Diirt repo

repository/cs-studio.product
=> Add new trayicon feature.

pom.xml
@willrogers #284 moved to the existing branch
=> Move diirt into profile (c.f. core/applications)

plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/editparts/MenuMuxEditPart.java
@willrogers 
c.f. cs-studio #2276 (https://github.com/ControlSystemStudio/cs-studio/issues/2276)
=> Disable combobox change on mousewheel scroll

pom.xml
=> Add diirt repo explicitly to product pom.xml.

plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/Messages.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/WindowSpecParser.java
=> Openwindow messages

plugins/org.csstudio.dls.product.common/plugin_customization.ini
=> Db config (integration)

pom.xml
=> Update Dawn p2 server to alfred.diamond.ac.uk (integration)

repository/cs-studio.product
=> Force product to use GTK2 as GTK3 is not yet supported (master)

plugins/org.csstudio.dls.product.common/plugin_customization.ini
=> Only primary archiver as default (master)

plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/editparts/MenuMuxEditPart.java
=> Mousewheel (master)

pom.xml
=> Update Dawn p2 server to alfred.diamond.ac.uk

plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/Messages.java, plugins/org.csstudio.openfile.newwindow/src/org/csstudio/openfile/newwindow/WindowSpecParser.java
=> Correct use of messages in newwindow plugin.

features/org.csstudio.dls.feature/feature.xml, plugins/org.csstudio.trends.databrowser2.command/META-INF/MANIFEST.MF
=> Remove javax.mail from feature and add as explicit Import

plugins/org.csstudio.dls.product.dev/META-INF/MANIFEST.MF, plugins/org.csstudio.dls.product.dev/plugin.properties
@willrogers Clean up some old text
=> Remove legacy EPIPCS port text from bundle

plugins/org.csstudio.dls.product.common/plugin_customization.ini
=> Add Archiver Appliance to list of databrowser data sources.

plugins/org.csstudio.dls.product.common/plugin_customization.ini
=> Add Archiver Appliance to list of databrowser data sources. 

plugins/org.csstudio.dls.product.common/plugin_customization.ini
=> Add name to each configured archive source

features/org.csstudio.dls.feature/feature.xml, plugins/org.csstudio.trends.databrowser2.command/META-INF/MANIFEST.MF
=> Javax mail

plugins/org.csstudio.dls.product.common/plugin_customization.ini
As https://github.com/dls-controls/org.csstudio.dls.product/pull/303 but hopefully with correctly formatted names.
=> Add Archiver Appliance to list of databrowser data sources - II (master)

plugins/org.csstudio.dls.product.common/plugin_customization.ini
=> Update AA URL to archappl.diamond.ac.uk

plugins/org.csstudio.dls.product.common/plugin_customization.ini
=> Update AA URL to archappl.diamond.ac.uk (master)

plugins/org.csstudio.dls.product.common/plugin.xml
As https://github.com/dls-controls/org.csstudio.dls.product/pull/314 but for master.
=> Don't show OPIShellSummary in OPIRuntime perspective.

plugins/org.csstudio.dls.product.common/plugin_customization.ini
Add URLs to databrowser configuration for two production archivers.
=> Added additional EPICS archiver appliances

plugins/org.csstudio.dls.product.common/plugin_customization.ini
=> Set default channel archiver to be All-ArchiveEngine.

plugins/org.csstudio.dls.product.common/plugin_customization.ini
@mfurseman I'm merging this to try to get a nightly build tonight.
=> Update archiver configuration.

features/org.csstudio.dls.product.feature/build.properties, features/org.csstudio.dls.product.feature/rootfiles/configuration/edm-colors.list, features/org.csstudio.dls.product.feature/rootfiles/edm-converter.sh
@mfurseman here's the wrapper script.
=> Converter app

features/org.csstudio.dls.product.feature/build.properties
=> Correct permissions handling on scripts.

plugins/org.csstudio.dls.product.common/plugin_customization.ini
@ifmalcuaz merging the change into the `integration-4.5.x` branch will trigger a nightly build where we can test the changes.
This commit changes the URLs for the EPICS archiver.
=> Archiver urls

features/org.csstudio.dls.product.feature/feature.xml, plugins/org.csstudio.archive.reader.fastarchiver.test/META-INF/MANIFEST.MF, plugins/org.csstudio.archive.reader.fastarchiver/META-INF/MANIFEST.MF, plugins/org.csstudio.dls.product.common/META-INF/MANIFEST.MF, plugins/org.csstudio.dls.product.dev/META-INF/MANIFEST.MF, plugins/org.csstudio.dls.product/META-INF/MANIFEST.MF, plugins/org.csstudio.logbook.dls/META-INF/MANIFEST.MF, plugins/org.csstudio.openfile.newwindow.test/META-INF/MANIFEST.MF, plugins/org.csstudio.openfile.newwindow/META-INF/MANIFEST.MF, plugins/org.csstudio.opibuilder.dlsopitests/META-INF/MANIFEST.MF, plugins/org.csstudio.opibuilder.widgets.dawn/META-INF/MANIFEST.MF, plugins/org.csstudio.opibuilder.widgets.edm/META-INF/MANIFEST.MF, plugins/org.csstudio.trends.databrowser2.command/META-INF/MANIFEST.MF, plugins/org.diirt.datasource.fa.test/META-INF/MANIFEST.MF, plugins/org.diirt.datasource.fa/META-INF/MANIFEST.MF, pom.xml, repository/cs-studio.product
@ifmalcuaz just for your information this merge allows me to build the DLS product against the master branches of the other repos.
=> 2530 jdk11

plugins/org.csstudio.opibuilder.widgets.dawn/META-INF/MANIFEST.MF, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/intensitygraph/DawnIntensityGraphEditPart.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/DawnXYGraphEditPart.java, plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/xygraph/XYGraphDataProvider.java, pom.xml
@rjwills28 this built successfully. I have checked quite a few XY graphs and they all seem to work ok, so I will merge this.
=> Updating dawn widgets to build against the Eclipse Nebula release

plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/Activator.java, plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/editparts/EdmSymbolEditpart.java, plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/figures/EdmSymbolFigure.java, plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/model/EdmSymbolModel.java
=> Css422 edm widget visibility

LICENSE
This matches the license in the cs-studio repo.
=> Add Eclipse Public License.

plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/figures/EdmSymbolFigure.java
This looks to have fixed the problem.
cc @rjwills28 @aawdls @MJGaughran
=> Css584 symbol widget issue
