dls-controls/org.csstudio.dls.product

- repository/cs-studio.p2.inf
Attempted fix for the issues requiring the $user/.eclipse/configuration directory to be emptied before a new nightly build can be executed.
(corresponding change made to build script to execute cs-studio -initialize)
> Set sharedConfiguration in release directory

- plugins/org.csstudio.opibuilder.widgets.dawn/META-INF/MANIFEST.MF
- plugins/org.csstudio.opibuilder.widgets.dawn/plugin.xml
- plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/actions/AbstractXYGraphTargetAction.java
- plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/actions/AbstractXYGraphWidgetTargetAction.java
- plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/actions/ClearXYGraphAction.java
- plugins/org.csstudio.opibuilder.widgets.dawn/src/org/csstudio/opibuilder/widgets/dawn/actions/ShowXYGraphToolbarAction.java
These are copied with the exception of a cast from the corresponding actions on the opibuilder widgets:
`org.csstudio.opibuilder.widgets.actions.ShowXYGraphToolbarAction`
`org.csstudio.opibuilder.widgets.actions.ClearXYGraphActio`
> Add right click actions to show/hide toolbar on Dawn XYGraph

- features/org.csstudio.dls.feature/feature.xml
It changes the order of diirt configuration meaning that the wrong
diirt configuration directory is used.
Fixing this is another matter that I'm not going to be able to do today.
@nickbattam @mfurseman
> Remove fa datasource from product.

- repository/cs-studio.product
The only reason to do this is to ensure that the integration
and dls-4.2.x branches are the same.
> Rearrange ordering of feature in cs-studio.product

- plugins/org.csstudio.dls.product/default_widgets.opi
This adds the 'Show Down Arrow' option to our OPI scheme so that it is shown by default when creating new widgets. Note that the default behaviour is not to show the down arrow to maintain backwards compatibility.
> Add menu button down arrow to OPI schema

- pom.xml
I don't fully understand whether this would be safe if we tried to compile files that weren't UTF-8-encoded.  However, this is what the internet recommends and it removes Maven warnings.
> Set file encoding to UTF-8.

- plugins/org.csstudio.dls.product/META-INF/MANIFEST.MF
This reverts commit 7acd22c0ca5627f7f26e8fcc598395ca3615fd66.
This was properly fixed by Eric in Diirt.
> Revert "Add antlr to DLS product dependencies."

- features/org.csstudio.dls.feature/feature.xml
This reverts commit 09eb5ecce905be08480f474cd42c4677f447d7b8.
Previous incompatibility with diirt configuration has been fixed.
> Revert "Remove fa datasource from product."

- plugins/org.csstudio.dls.product/default_widgets.opi
This merges the changes from pull request #52 into the dls-4.2.x branch.
This adds the 'Show Down Arrow' option to our OPI scheme so that it is shown by default when creating new widgets. Note that the default behaviour is not to show the down arrow to maintain backwards compatibility.
> Add menu button down arrow to OPI schema - DLS-4.2.x

- plugins/org.csstudio.dls.product/plugin.xml
There is a org.eclipse.team.ui plugin which is included in org.eclipse.search, a commonly used component in CS-Studio. We can't very easily remove this plugin from the build as it's required by opibuilder amongst other things, however we can hide the views and perspective it creates but nobody has any use for!
This hides the '_Team Synchronizing_' perspective, and the '_History_' and '_Synchronise_' views.
> Prevent team synchronizing perspective and views from showing

- plugins/org.csstudio.dls.product/plugin.xml
This adds a list of perspectives and views which are always shown under the Window menu, along with the 'Other...' selector.
By having a fixed order of perspectives, and showing the perspective which is currently selected in the menu, the user should feel more confident that they can navigate between perspectives and return to the current perspective. The navigator and console views are also shown by default.
> Better default perspectives and views under the Window menu - [integration]

- plugins/org.csstudio.dls.product/plugin.xml
This adds the standalone OPI summary in all four default perspectives, it also isn't closeable, so you should never find yourself in a situation where your workbench window bindings have been lost from an OPI shell.
We should see how invasive this is before thinking about merging to master!
> Keep Standalone OPI Summary open in all perspectives - [integration]

- plugins/org.csstudio.dls.product.5064/plugin_customization.ini
- plugins/org.csstudio.dls.product.6064/plugin_customization.ini
As it happens this didn't make any difference, but this is semantically
correct - we pick the key of the default engine, which in fact points
to the entire archive anyway.
@nickbattam
> Use correct keys for default archive engines.

- plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/editparts/EdmSymbolEditpart.java
- plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/model/EdmSymbolModel.java
Our typical use case for a symbol widget is to enter a PV into the PV Name field, and then set up a rule which monitors the same PV and maps that PV value to an image index to be shown. This allows us to use the right click context menu and tooltips to interact with the PV while also having custom behaviour.
The problem with the above scenario is that there is a race condition where the PV update can be applied after the rule, and the wrong image index is shown. This only seems to occur on OPI's with few widgets.
This pull request changes the widget so that the connected PV has no effect on which image is shown, and this is instead updated by an image_index property, that can then be controlled by a rule.
> CSS-294: Change DLS Symbol widget to update by index, not PV value

- plugins/org.csstudio.trends.databrowser2.command/META-INF/MANIFEST.MF
- plugins/org.csstudio.trends.databrowser2.command/src/org/csstudio/trends/databrowser2/command/NewWindowHandler.java
This had failed when a plot file was being manually copied into place
and the Eclipse workspace had not been refreshed.
@nickbattam
> Refresh workspace when loading plot file from script.

- plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/editparts/EdmSymbolEditpart.java
This reverts commit 1ab8cf934ee27dd9f93a6edc95fc87a3c41059b0.
Incorrect copy of checkstyle branch (#166) onto master. EdmSymbolEditpart has changed between 4.3 and 4.4.
> Revert "Remove unused imports"

- features/org.csstudio.dls.product.feature/rootfiles/css.sh
@willrogers Add argument to flush cached preferences before loading.
Is this the correct default behaviour, or should the meaning of the flag be flipped to 'preserve diirt config' when set?
> Extend launch script to delete cached DIIRT/EPICS preferences

- plugins/org.csstudio.dls.product.common/plugin_customization.ini
They were removed by default in Eclipse Neon. @nickbattam
> Ensure perspective names are shown in the UI.

- features/org.csstudio.dls.feature/feature.xml
- plugins/org.csstudio.trends.databrowser2.command/META-INF/MANIFEST.MF
@willrogers This fixes the missing javax.mail error in the offline build. I have successfully run an offline build with this patch.
Removing javax.mail from feature and adding it as an explicit Import doesn't look like the right approach; it's patching an issue rather than understanding why the databrowser2 dependence on javax.mail isn't being managed correctly when we pull it from applications.
> javax.mail build issues

- plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/editparts/MenuMuxEditPart.java
- plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/figures/MenuMuxFigure.java
- plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/model/MenuMuxModel.java
@willrogers, @mfurseman  MenuMux is now disabled if any of the attached PVs (target or controlPV) are read-only and updates ALL target PVs when the control PV (PV_NAME) is updated.
> Mmux enabling

- plugins/org.csstudio.dls.product.common/plugin.xml
@nickbattam @mfurseman this means that if you open a screen in a new workbench window, all you get is that screen. The right-clicks seem to work, but I know it is possible to lose the right-clicks sometimes, I just haven't managed to pinpoint when.
> Don't show OPIShellSummary in OPIRuntime perspective.

- features/org.csstudio.dls.product.feature/rootfiles/css.sh
- repository/cs-studio.product
This changes the previous build-fixes branch to use the --launcher.appendVmargs, instead of just moving them all out into the css.sh wrapper script.
> Make sure we specify all vm args

- features/org.csstudio.dls.product.feature/rootfiles/css.sh
This behaviour will be more consistent, and helps when trying to launch a
particular perspective on launch since it doesn't need to load a previous one
first.
@mfurseman this is included in the nightly build, and seems to me to be working fine.
> Clear workbench state before launching each time.

- repository/cs-studio.p2.inf
Gets rid of the preferences update site.
> remove eclipse 3.3 update site in preferences dialog

- features/org.csstudio.dls.product.feature/rootfiles/css.sh
Use gdbus to figure out if cs-studio is running in the current session. Use gnome-terminal only if so, to prevent unwanted workspace switches.
> Css582 screen launching

- plugins/org.csstudio.opibuilder.widgets.edm/src/org/csstudio/opibuilder/widgets/edm/editparts/EdmSymbolEditpart.java
In some cases ghost EDM Symbols can be clicked on and activated in containers that they do no belong to. This is a work around to fix this issue as the true problem lies in the eclipse draw2d package.
> Fix the interaction with ghost EDM symbol widgets

- plugins/org.csstudio.dls.product.common/plugin_customization.ini
This will allow CS-Studio to subscribe to property updates in the IoC and pick up runtime changes. This relates to an issue discovered where a dropdown menu populated with enum values did not update as the enum labels changed at run time. 
This change will support getting property updates by default in the DLS instance of CS-Studio.
> Adding a default property to configure diirt to subscribe to property updates

- pom.xml
The URL for CSS dependency packages has been taken offline. This PR replaces the URL for diirt with an internal P2 mirror to allow CSS builds to complete in Jenkins.
This code has been tested in Jenkins and the integration build jobs now pass: https://jenkins.diamond.ac.uk/view/CS-Studio/
Old Link: http://diirt.download.controlsystemstudio.org/diirt/3.1.7
New Link: https://alfred.diamond.ac.uk/sites/diirt.download.controlsystemstudio.org/diirt/3.1.7
> Update diirt repo to use Diamond p2 mirror

- repository/cs-studio.product
Two properties have been added for CSS startup:
- Property to disable validation of JAR files. This check is performed in later versions of Java and fails for the jython-standalone.jar plugin that CSS depends on. This causes runtime issues when using CSS. The later version of the jython-standalone package also do not pass these checks therefore the only workaround to ensure CSS works on later versions of Java is to set this property.
- Property to set the socket connection timeout when establishing a TCP connection. This is used with the latest version of the JCA plugin (2.4.10), which has just been pulled into the latest CSS build config. For DLS we want this timeout to be 3 secs.
> Add DLS specific properties to CS-Studio ini file
